name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
  
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, macos-latest]
        swift: ["6.0"]
    
    steps:
      - uses: actions/checkout@v4
    
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
    
      - run: swift --version

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
