name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
     - uses: swift-actions/setup-swift@v2
     - name: Build
       run: swift build -v
     - name: Run tests
       run: swift test -v
